apiVersion: v1
kind: Secret
metadata:
  labels:
    template: cronjob-aws-ocp-snap
  name: aws-secret
stringData:
  access_key: {{ .Values.aws_secret_access_key }}
  key_id: {{ .Values.aws_access_key_id }}
  region: {{ .Values.aws_region }}
